name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v5

    - name: Install dependencies
      run: flutter pub get

    - name: Build and Deploy
      run: |
        flutter build apk --release
        curl -L bashupload.com -T build/app/outputs/flutter-apk/*.apk

    - name: Deploy to GitHub Releases
      uses: softprops/action-gh-release@v1
      with:
        files: build/app/outputs/flutter-apk/app-release.apk
        token: ${{ secrets.REPO_TOKEN }}
